test_0 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for file creation: ./lab3a.py ... ok
test_1 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for errors running: ./lab3a.py ... ok
test_2 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for correct shebang line: ./lab3a.py ... ok
test_4_function_return_text_value (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output ... ERROR

======================================================================
ERROR: test_4_function_return_text_value (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/james/ops445/lab3/./CheckLab3.py", line 79, in test_4_function_return_text_value
    self.assertEqual(lab3aStudent.return_text_value(), expected_output, msg=error_output)
AttributeError: module 'lab3a' has no attribute 'return_text_value'

----------------------------------------------------------------------
Ran 4 tests in 0.014s

FAILED (errors=1)
OPS445 Lab Report - System Information for running ./CheckLab3.py
=================================================================
    User login name: james
    Linux system name: james-VM
    Python executable: /usr/bin/python3
    Python version: 31012
    OS Platform: linux
    Working Directory: /home/james/ops445/lab3
    Start at: Thu May 30 18:03:11 2024
=================================================================
hot
perfect
cold
ok
ok
